version: '3'
services:
  database:
    restart: always
    image: postgis/postgis:13-master
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: 'directus'

  cache:
    restart: always
    image: redis:6
    networks:
      - directus

  directus:
    restart: always
    image: directus/directus:latest
    ports:
      - '7455:8055'
    volumes:
      - uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '${KEY}'
      SECRET: '${SECRET}'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: '${DB_PASSWORD}'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      CACHE_AUTO_PURGE: 'true'

      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      
      EMAIL_FROM: '${EMAIL_FROM}'
      EMAIL_TRANSPORT: smtp
      EMAIL_SMTP_HOST: mail
      EMAIL_SMTP_PORT: 587
      
      REFRESH_TOKEN_COOKIE_SAME_SITE: '${REFRESH_TOKEN_COOKIE_SAME_SITE}'
      REFRESH_TOKEN_COOKIE_SECURE: '${REFRESH_TOKEN_COOKIE_SECURE}'
      # Make sure to set this in production
      # (see https://docs.directus.io/reference/environment-variables/#general)
      PUBLIC_URL: 'https://${PUBLIC_URL}'

  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - directus
    environment:
      RELAY_PORT: 587

  lap:
    image: fauria/lap:latest
    restart: always
    ports:
      - '7480:80'
    volumes:
      - lap:/var/www/html
  demo:
    image: fauria/lap:latest
    restart: always
    ports:
      - '7481:80'
    volumes:
      - demo:/var/www/html


networks:
  directus:

volumes:
  uploads:
  db:
  lap:
  demo:
